name: DRAW-office
favicon: null
layout_spectrum: 0.49984
typography_spectrum: 0.23404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6d6e70'
    - '#c2c3c5'
    - '#cddf6d'
    - '#87888b'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.9860210511833429
purpose: []
